convidados = ['jesus', 'buda', 'enoque', 'moises', 'abrahao', 'fred mercury', 'elon musk']
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[0].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[1].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[2].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[3].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[4].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[5].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'Boa noite, o nosso anfitrião gostaria de convidar {convidados[6].title()} para um jantar para passarmos um momento na companhia um do outro.')
print(f'\nInfelizmente gostaria de informar que {convidados[0].title()}, {convidados[1].title()}, {convidados[3].title()}, não irão ao evento por motivos maiores, espero que entenda a situação.')
convidados.remove('jesus')
convidados.remove('buda')
convidados.remove('moises')
convidados.insert(0, 'professor x')
convidados.insert(1, 'são paulo')
convidados.insert(3, 'krishina')
print(convidados)
print(f"Com muitas honras gostariamos de convidar os ilustres {convidados[0].title()} para o nosso encontro avançado para uma conversa. ")
print(f"Com muitas honras gostariamos de convidar os ilustres {convidados[1].title()} para o nosso encontro avançado para uma conversa. ")
print(f"Com muitas honras gostariamos de convidar os ilustres {convidados[3].title()} para o nosso encontro avançado para uma conversa. ")
print(f'Gostariamos de informar ao {convidados} que foi coloca uma mesa extra ao nosso encontro, podendo assim ser integrado mais honras ao nosso encontro. ')
convidados.insert(0, 'Platão')
convidados.insert(4, 'paracelso')
convidados.append('amonio sacas')
print(convidados)
print(f'Com muita honra informamos ao {convidados[0].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[1].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[2].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[3].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[4].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[5].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[6].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[7].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')
print(f'Com muita honra informamos ao {convidados[8].title()} que foi finalizado os convites e não vejo a hora de nos encontrarmos para a nossa conversa vital, muito agradecido pela presença de todos')

print('\n\n\n--------------------------------------\n')
print(f'Para os nossos Convidados, {convidados}, infelizmente e felizmente Deus me deu a chance de conhecer apenas dois dos grandes que escolhi, peço humildemente desculpas e em breve enviarei a lista com os dois escolhidos.')
primeiro_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {primeiro_retirado}.')
segundo_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {segundo_retirado}.')
terceiro_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {terceiro_retirado}.')
quarto_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {quarto_retirado}.')
quinto_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {quinto_retirado}.')
sexto_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {sexto_retirado}.')
setimo_retirado = convidados.pop()
print(f'infelizmente iremos marcar uma proxima vez {setimo_retirado}.')
oitavo_retirado = convidados.remove('professor x')
print(f'infelizmente iremos marcar uma proxima vez {oitavo_retirado}.')
()
print(convidados)
print(f'Com muitas honras informamos que teremos uma noite mais que agradavel de muita sabedoria {convidados[0].title()}, agradecido, nos vemos em breve.')
print(f'Com muitas honras informamos que teremos uma noite mais que agradavel de muita sabedoria {convidados[1].title()}, agradecido, nos vemos em breve.')
del convidados[0]
del convidados[0]

print(convidados)




