names_friends = ["João", "Filipe", "Guilherme", "Medina", "Danilo", "ViniciusB", "vinicimM", "Pimenta", "Cruz", "vinny", "guilol", "gustavão"]
print(names_friends[-1].title())
print(names_friends[0])
print(names_friends[1])
print(names_friends[2])
print(names_friends[3])
print(names_friends[4])
print(names_friends[5])
print(names_friends[6])
print(names_friends[7])
print(names_friends[8])
print(names_friends[9].title())
print(names_friends[10].title())