cars = ["bmw", "audi", "toyota", "subaru"]
# cars.sort()
# cars.sort(reverse=True)
# print(cars)
# nomes = ["zidani", "joaquim", "fabricio", "fernando", "bruno", "ana"]
# nomes.sort()
# print(cars)
print(f"this is the original list: {cars}")
print(f"\nthis is the sorted list: {sorted(cars)}")
print(f"\nHere is the original list again: {cars}\n")
print(sorted(cars, reverse=True))
cars.reverse()
print(cars)
cars.reverse()
print(cars)