paises = ["estados unidos da america", "china", "italia", "israel", "canada", "chile", "australia"]
print(paises)
print(sorted(paises))
print(paises)
print(sorted(paises, reverse=True))
print(paises)
paises.reverse()
print(paises)
paises.reverse()
print(paises)
paises.sort()
print(paises)
paises.sort(reverse=True)
print(paises)